config/routes.rb
Flowfree::Application.routes.draw do
  devise_for :users

  root to: 'site#index'

  post '/rivers/subscribe_to_gauge/:site_code', to: 'rivers#subscribe_to_gauge', as: 'subscribe'

  post '/rivers/unsubscribe_from_gauge/:site_code', to: 'rivers#unsubscribe_from_gauge', as: 'unsubscribe'

  post '/rivers/update_subscription', to: 'rivers#update_subscription', as: 'update'

  get '/rivers/by_state/:state', to: 'rivers#index', as: 'get_rivers_by_state'
  post '/rivers/by_state', to: 'rivers#post_to_state', as: 'rivers_by_state'

  get '/rivers/by_name/:search', to: 'rivers#search', as: 'get_rivers_by_name'
  post '/rivers/by_name', to: 'rivers#post_to_name', as: 'rivers_by_name'

  get '/rivers/by_state_and_name/:state/:search', to: 'rivers#search', as: 'get_rivers_by_state_and_name'
  post '/rivers/by_state_and_name', to: 'rivers#post_to_state_and_name', as: 'rivers_by_state_by_name'

  resources :rivers, :except => :index

  get '/users/sign_in', to: 'devise/sessions#new', as: 'sign_in'
  get '/users/sign_up', to: 'devise/registrations#new', as: 'sign_up'
  match '/users/sign_out', to: 'devise/sessions#destroy', as: 'sign_out', via: 'delete'
  get '/users/:id', to: 'users#show', as: 'user_profile'

  resources :users

end

app/models/river.rb
class River < ActiveRecord::Base
  include RiversHelper
  self.primary_key = "site_code"
  has_many :users,
           :through => "subscriptions",
           :foreign_key => "site_code"
  has_many :river_times,
           :foreign_key => "site_code"


  def state
    full_name(self[:state])
  end

  def self.recent
    self.order(:created_at => :desc).group(:site_code)
  end

  def self.search(search)
    if search
      find(:all, :conditions => ['Name like ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/controllers/rivers_controller.rb
class RiversController < ApplicationController
  before_action :set_river, only: [:show, :edit, :update, :destroy]

  # GET /rivers
  # GET /rivers.json
  def index
    @rivers = River.where(:state => params[:state]).paginate(:page => params[:page])
  end

  # GET /rivers/1
  # GET /rivers/1.json
  def show
  end

  def post_to_state
    redirect_to get_rivers_by_state_path(params[:state])
  end

  def post_to_name
    redirect_to get_rivers_by_name_path(params[:search])
  end

  def post_to_state_and_name
    redirect_to get_rivers_by_state_and_name_path(params[:state], params[:search])
  end

  def search
    @rivers = River.all.paginate(:page => params[:page])
    if params[:search].present?
      # find me a thing that starts with some stuff & ends with some stuff & has :search in middle
      @rivers = @rivers.where('site_name LIKE ?', "%#{params[:search]}%")
    end
    if params[:state].present?
      # find me a thing that starts with some stuff & ends with some stuff & has :search in middle
      @rivers = @rivers.where(state: params[:state])
    end

    render :index
  end

  # GET /rivers/new
  def new
    @river = River.new
  end

  # GET /rivers/1/edit
  def edit
    session[:return_to] = request.referer
  end

  # POST /rivers
  # POST /rivers.json
  def create
    @river = River.new(river_params)

    respond_to do |format|
      if @river.save
        format.html { redirect_to @river, notice: 'River was successfully created.' }
        format.json { render action: 'show', status: :created, location: @river }
      else
        format.html { render action: 'new' }
        format.json { render json: @river.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rivers/1
  # PATCH/PUT /rivers/1.json
  def update
    respond_to do |format|
      if @river.update(river_params)
        format.html { redirect_to @river, notice: 'River was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @river.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rivers/1
  # DELETE /rivers/1.json
  def destroy
    @river.destroy
    respond_to do |format|
      format.html { redirect_to rivers_url }
      format.json { head :no_content }
    end
  end

  def subscribe_to_gauge
    session[:return_to] ||= request.referer
    Subscription.create(user_id: current_user.id, site_code: params[:site_code])
    redirect_to(session.delete(:return_to) || default)
  end

  def unsubscribe_from_gauge
    session[:return_to] ||= request.referer
    Subscription.find_by(user_id: current_user.id, site_code: params[:site_code]).destroy
    redirect_to(session.delete(:return_to) || default)
  end

  def update_subscription
    session[:return_to] ||= request.referer
    subscription = Subscription.find_by(user_id: current_user.id, site_code: params[:site_code])
    subscription.update(floor: params[:floor], ceiling: params[:ceiling])
    subscription.save
    redirect_to(session.delete(:return_to) || default)
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_river
      @river = River.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def river_params
      params.require(:river).permit(:site_name, :site_code, :refresh_time, :latitude, :longitude, :srs, :county_id, :cfs_value, :state)
    end
end

app/helpers/rivers_helper.rb
module RiversHelper
  def us_states
  [
    [ "Alabama", "al" ],
    [ "Alaska", "ak" ],
    [ "Arizona", "az" ],
    [ "Arkansas", "ar" ],
    [ "California", "ca" ],
    [ "Colorado", "co" ],
    [ "Connecticut", "ct" ],
    [ "Delaware", "de" ],
    [ "Florida", "fl" ],
    [ "Georgia", "ga" ],
    [ "Hawaii", "hi" ],
    [ "Idaho", "id" ],
    [ "Illinois", "il" ],
    [ "Indiana", "in" ],
    [ "Iowa", "ia" ],
    [ "Kansas", "ks" ],
    [ "Kentucky", "ky" ],
    [ "Louisiana", "la" ],
    [ "Maine", "me" ],
    [ "Maryland", "md" ],
    [ "Massachusetts", "ma" ],
    [ "Michigan", "mi" ],
    [ "Minnesota", "mn" ],
    [ "Mississippi", "ms" ],
    [ "Missouri", "mo" ],
    [ "Montana", "mt" ],
    [ "Nebraska", "ne" ],
    [ "Nevada", "nv" ],
    [ "New Hampshire", "nh" ],
    [ "New Jersey", "nj" ],
    [ "New Mexico", "nm" ],
    [ "New York", "ny" ],
    [ "North Carolina", "nc" ],
    [ "North Dakota", "nd" ],
    [ "Ohio", "oh" ],
    [ "Oklahoma", "ok" ],
    [ "Oregon", "or" ],
    [ "Pennsylvania", "pa" ],
    [ "Rhode Island", "ri" ],
    [ "South Carolina", "sc" ],
    [ "South Dakota", "sd" ],
    [ "Tennessee", "tn" ],
    [ "Texas", "tx" ],
    [ "Utah", "ut" ],
    [ "Vermont", "vt" ],
    [ "Virginia", "va" ],
    [ "Washington", "wa" ],
    [ "West Virginia", "wv" ],
    [ "Wisconsin", "wi" ],
    [ "Wyoming", "wy" ]
  ]
  end

  def full_name(state_abrev)
    us_states.select { |state| state[1] == state_abrev }.first.first
  end

  def us_states_hash
  [
    { :name => "Alabama",
        :id => "al" },
    { :name => "Alaska",
        :id => "ak" },
    { :name => "Arizona",
        :id => "az" },
    { :name => "Arkansas",
        :id => "ar" },
    { :name => "California",
        :id => "ca" },
    { :name => "Colorado",
        :id => "co" },
    { :name => "Connecticut",
        :id => "ct" },
    { :name => "Delaware",
        :id => "de" },
    { :name => "Florida",
        :id => "fl" },
    { :name => "Georgia",
        :id => "ga" },
    { :name => "Hawaii",
        :id => "hi" },
    { :name => "Idaho",
        :id => "id" },
    { :name => "Illinois",
        :id => "il" },
    { :name => "Indiana",
        :id => "in" },
    { :name => "Iowa",
        :id => "ia" },
    { :name => "Kansas",
        :id => "ks" },
    { :name => "Kentucky",
        :id => "ky" },
    { :name => "Louisiana",
        :id => "la" },
    { :name => "Maine",
        :id => "me" },
    { :name => "Maryland",
        :id => "md" },
    { :name => "Massachusetts",
        :id => "ma" },
    { :name => "Michigan",
        :id => "mi" },
    { :name => "Minnesota",
        :id => "mn" },
    { :name => "Mississippi",
        :id => "ms" },
    { :name => "Missouri",
        :id => "mo" },
    { :name => "Montana",
        :id => "mt" },
    { :name => "Nebraska",
        :id => "ne" },
    { :name => "Nevada",
        :id => "nv" },
    { :name => "New Hampshire",
        :id => "nh" },
    { :name => "New Jersey",
        :id => "nj" },
    { :name => "New Mexico",
        :id => "nm" },
    { :name => "New York",
        :id => "ny" },
    { :name => "North Carolina",
        :id => "nc" },
    { :name => "North Dakota",
        :id => "nd" },
    { :name => "Ohio",
        :id => "oh" },
    { :name => "Oklahoma",
        :id => "ok" },
    { :name => "Oregon",
        :id => "or" },
    { :name => "Pennsylvania",
        :id => "pa" },
    { :name => "Rhode Island",
        :id => "ri" },
    { :name => "South Carolina",
        :id => "sc" },
    { :name => "South Dakota",
        :id => "sd" },
    { :name => "Tennessee",
        :id => "tn" },
    { :name => "Texas",
        :id => "tx" },
    { :name => "Utah",
        :id => "ut" },
    { :name => "Vermont",
        :id => "vt" },
    { :name => "Virginia",
        :id => "va" },
    { :name => "Washington",
        :id => "wa" },
    { :name => "West Virginia",
        :id => "wv" },
    { :name => "Wisconsin",
        :id => "wi" },
    { :name => "Wyoming",
        :id => "wy" }
    ]
  end

  def markers_for_static_map(rivers)
    rivers.map { |river| river.latitude + ',' + river.longitude }.join('|')
  end

  def markers_for_profile_map(subscriptions)
    subscriptions.map { |subscription| subscription.river.latitude + ',' + subscription.river.longitude }.join('|')
  end
end

app/views/rivers/_form.html.erb
<%= form_for(@river) do |f| %>
  <% if @river.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@river.errors.count, "error") %> prohibited this river from being saved:</h2>

      <ul>
      <% @river.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :site_name %><br>
    <%= f.text_field :site_name %>
  </div>
  <div class="field">
    <%= f.label :site_code %><br>
    <%= f.text_field :site_code %>
  </div>
  <div class="field">
    <%= f.label :refresh_time %><br>
    <%= f.datetime_select :refresh_time %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :srs %><br>
    <%= f.text_field :srs %>
  </div>
  <div class="field">
    <%= f.label :county_id %><br>
    <%= f.text_field :county_id %>
  </div>
  <div class="field">
    <%= f.label :cfs_value %><br>
    <%= f.text_field :cfs_value %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rivers/edit.html.erb
<h1>Editing river</h1>

<%= render 'form' %>

<%= link_to 'Show', @river %> |
<%= link_to 'Back', rivers_path %>

app/views/rivers/index.html.erb
<% content_for :title do %>
<% if params[:state] != nil && params[:search] != nil %>
Sites in <%= params[:state].upcase %> that match: '<%= params[:search] %>'
<% end %>
<% if params[:state] != nil && params[:search] == nil %>
Sites in <%= params[:state].upcase %>
<% elsif params[:search] != nil && params[:state] == nil %>
Sites Matching '<%= params[:search] %>'
<% end %>
<% end %>
<div class="row">

</div>
<div class="row">
  <div class="large-8 large-offset-2 columns">
    <h4>Gauge Locations</h4>
    <div class="state-map">
      <%= image_tag("http://maps.googleapis.com/maps/api/staticmap?size=980x400&maptype=hybrid&sensor=false&markers=#{markers_for_static_map(@rivers)}", alt: "Map markers for #{params[:search]} in #{params[:state]}")%>
    </div>
  </div>
  <!-- <div class="large-6 columns">
      <h4>Info</h4>
    <div class="state-info">

    </div>

  </div> -->
</div>

<div class="row">
  <div class="large-8 large-offset-2 columns state-gage-table">
    <% if params[:state] != nil && params[:search] != nil %>
    <h4>Sites in <%= params[:state].upcase %> that match: '<%= params[:search] %>' </h4>
    <% end %>
    <% if params[:state] != nil && params[:search] == nil %>
    <h4>Sites in <%= params[:state].upcase %></h4>
    <%= form_tag rivers_by_state_by_name_path do %>
    <%= text_field_tag :search, params[:search], :placeholder => "Search #{params[:state].upcase} sites here..." %>
    <%= hidden_field_tag :state, params[:state] %>
    <%= submit_tag "Search", :name => nil, class: 'small button searchbutton' %>
    <% end %>
    <% end %>
    <% if params[:search] != nil && params[:state] == nil %>
    <h4>Nationwide Search for: '<%= params[:search] %>'</h4>
    <% end %>
  </div>
  <div class="large-7 columns">
  </div>
</div>

<div class="row">
  <div class="large-12 columns">
    <table>
      <thead>
        <tr>
          <th>Site name</th>
          <th>Flow</th>
          <th>Site code</th>
          <th>Refresh time</th>
          <th>Latitude</th>
          <th>Longitude</th>
          <th>More info</th>
          <% if user_signed_in? %>
          <th>Follow</th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% @rivers.each do |river| %>
        <tr>
          <td><%= river.site_name %></td>
          <td><%= river.cfs_value %> cfs</td>
          <td><%= river.site_code %></td>
          <td><%= river.time %></td>
          <td><%= river.latitude %></td>
          <td><%= river.longitude %></td>
          <td><%= link_to 'Details', river, class: 'button tiny' %></td>
          <% if user_signed_in? %>
          <td>
            <% if current_user.subscribed?(river.site_code) %>
              <%= link_to 'Unsubscribe', unsubscribe_path(river.site_code), method: :post, class: 'button tiny', id: 'unsubscribe' %>
            <% else %>
              <%= link_to 'Subscribe', subscribe_path(river.site_code), method: :post, class: 'button tiny' %>
            <% end %>
          <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="row">
  <div class='large-12 columns text-center paginate'>
    <br/>
    <%= will_paginate @rivers, class:'pagination' %>
  </div>
</div>

app/views/rivers/new.html.erb
<h1>New river</h1>

<%= render 'form' %>

<%= link_to 'Back', rivers_path %>

app/views/rivers/search_view.html.erb
<!-- BEGINNING TO START A TEMPLATE FOR SEARCH FUNCTIONS TO DISPLAY BETTER TITLE 11:38 7/7 -->
<% content_for :title do %>
  Sites Matching '<%= params[:search] %>'
<% end %>
<div class="row">
  <div class="span10 offset1 text-center">
    <h2><%= @rivers.first.name %></h2>
  </div>
</div>

<div class="row">
  <div class="span6">
      <h4>Map</h4>
    <div class="state-map">
      <p>THIS IS A MAP OF <%= @rivers.first.state %></p>
    </div>
  </div>
  <div class="span6">
      <h4>Info</h4>
    <div class="state-info">
      <p><%= @rivers.first.state %> Graphs</p>
    </div>
  </div>
</div>

<div class="row">
  <div class="span12 state-gage-table">
    <%= form_tag rivers_by_state_by_name_path do %>
      <p>
        <%= text_field_tag :search, params[:search] %>
        <%= hidden_field_tag :state, params[:state] %>
        <%= submit_tag "Search", :name => nil %>
      </p>
      <% end %>
    <table>
      <thead>
        <tr>
          <th>Site name</th>
          <th>Site code</th>
          <th>Refresh time</th>
          <th>Latitude</th>
          <th>Longitude</th>
          <th>County</th>
          <th>Flow</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @rivers.each do |river| %>
          <tr>
            <td><%= river.site_name %></td>
            <td><%= river.site_code %></td>
            <td><%= river.refresh_time %></td>
            <td><%= river.latitude %></td>
            <td><%= river.longitude %></td>
            <td><%= river.county_id %></td>
            <td><%= river.cfs_value %>cfs</td>
            <td><%= link_to 'details', river %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
    <div class='span8 offset2'>
      <%= will_paginate @rivers %>
    </div>

app/views/rivers/show.html.erb
<% content_for :title do %>
  Details for <%= @river.site_name %>
<% end %>
<div id="state-show">
<div class="row">
  <div class="large-8 large-offset-2 columns title-content">
    <h2><%= @river.site_name %></h2>
    <br>
    <h3>Current Flow: <%= @river.cfs_value %> cfs </h3>
  </div>
</div>
<div class="row">
  <div class="large-4 content2 columns">
    <div id='square'>
      <%= image_tag("http://maps.googleapis.com/maps/api/staticmap?markers=#{@river.latitude},#{@river.longitude}&zoom=12&size=350x350&maptype=hybrid&sensor=false")%>
    </div>
    <p id="notice"><%= notice %></p>
    <p>
      <strong>State:</strong>
      <%= @river.state.titleize %>
    <br/>
      <strong>CFS value:</strong>
      <%= @river.cfs_value %> cfs
    <br/>
      <strong>Latitude:</strong>
      <%= @river.latitude %>
    <br/>
      <strong>Longitude:</strong>
      <%= @river.longitude %>
    <br/>
      <strong>Site code:</strong>
      <%= @river.site_code %>
    <br/>
      <strong>Refresh time:</strong>
      <%= @river.time %>
    <br/>
      <strong>County:</strong>
      <%= @river.county_id %>
    </p>
    <p>
      <% if user_signed_in? %>
        <% if current_user.subscribed?(@river.site_code) %>
          <%= link_to 'Unsubscribe', unsubscribe_path(@river.site_code), method: :post, class: 'button tiny', id: 'unsubscribe' %>
        <% else %>
          <%= link_to 'Subscribe', subscribe_path(@river.site_code), method: :post, class: 'button tiny' %>
        <% end %>
      <% end %>
    </p>
  </div>
  <div class="large-8 columns text-center">
      <%= image_tag("http://waterdata.usgs.gov/nwisweb/graph?agency_cd=USGS&site_no=#{@river.site_code}&parm_cd=00060&period=7", alt: "site graph for gauge number #{@river.site_code}") %>
    <div class="row">
      <div class="large-4 large-offset-4 graph-title">
        <h4>LAST 7 DAYS</h4>
      </div>
    </div>
  </div>
</div>
</div>