config/routes.rb
Flowfree::Application.routes.draw do
  devise_for :users

  root to: 'site#index'

  post '/rivers/subscribe_to_gauge/:site_code', to: 'rivers#subscribe_to_gauge', as: 'subscribe'

  post '/rivers/unsubscribe_from_gauge/:site_code', to: 'rivers#unsubscribe_from_gauge', as: 'unsubscribe'

  post '/rivers/update_subscription', to: 'rivers#update_subscription', as: 'update'

  get '/rivers/by_state/:state', to: 'rivers#index', as: 'get_rivers_by_state'
  post '/rivers/by_state', to: 'rivers#post_to_state', as: 'rivers_by_state'

  get '/rivers/by_name/:search', to: 'rivers#search', as: 'get_rivers_by_name'
  post '/rivers/by_name', to: 'rivers#post_to_name', as: 'rivers_by_name'

  get '/rivers/by_state_and_name/:state/:search', to: 'rivers#search', as: 'get_rivers_by_state_and_name'
  post '/rivers/by_state_and_name', to: 'rivers#post_to_state_and_name', as: 'rivers_by_state_by_name'

  resources :rivers, :except => :index

  get '/users/sign_in', to: 'devise/sessions#new', as: 'sign_in'
  get '/users/sign_up', to: 'devise/registrations#new', as: 'sign_up'
  match '/users/sign_out', to: 'devise/sessions#destroy', as: 'sign_out', via: 'delete'
  get '/users/:id', to: 'users#show', as: 'user_profile'

  resources :users

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/site/index.html.erb
<% provide(:title, "Current Conditions") %>

<div class="row">
  <div class="large-12 columns">
    <div id="googft-mapCanvas"></div>
    <hr>
  </div>
</div>
<div class="container content2">
<div class="row content">
  <div class="large-4 columns">
    <%= image_tag("flowing-river1.jpg", class: 'content-img') %>
  </div>
  <div class="large-8 columns">
    <h4>Search current flows of all rivers and streams in the USA</h4>
      <div class="row">
        <div class="large-6 columns">
          <p>Explore Current Conditions for any individual site in the country through the map above, or use the menus at right to browse all the sites in a state or perform a nationwide search of site names. Restrict your search to only one state on the individual state pages.</p>
        </div>
        <div class="large-6 columns">
          <div id='state-drop-dwn'>
            <%= form_tag rivers_by_state_path do %>
              <%= select_tag :state, options_for_select(us_states), :prompt => 'Select A State' %>
              <%= submit_tag("Go!", class: 'button tiny') %>
            <% end %>
            <%= form_tag rivers_by_name_path do %>
              <%= text_field_tag :search, params[:search], :placeholder => 'Search the nation...' %>
              <%= submit_tag("Search", class: 'button tiny') %>
           <% end %>
          </div>
        </div>
      </div>
  </div>
  </div>
  <div class="row content content-row2">
    <div class="large-8 columns">
      <h4>Create your own personalized gauge page</h4>
        <div class="row">
          <div class="large-6 columns">
            <p>Sign up for Current Conditions and get your own personal gauge table!</p>
            <div id="register"><%= link_to 'Register Now!', sign_up_path, :class => 'button large', :id => 'register-button' %></div>
          </div>
          <div class="large-6 columns">
            <p>Easily follow all the gauges on all the rivers that matter to you! Have them all displayed in one handy table whenever you sign in! Even get email updates when flows rise or fall above a discharge level set by you! Always know your favorite flows!</p>
          </div>
        </div>
    </div>
    <div class="large-4 columns">
      <%= image_tag("raft.jpg", class: 'content-img') %>
    </div>
  </div>
</div>