config/routes.rb
Flowfree::Application.routes.draw do
  devise_for :users

  root to: 'site#index'

  post '/rivers/subscribe_to_gauge/:site_code', to: 'rivers#subscribe_to_gauge', as: 'subscribe'

  post '/rivers/unsubscribe_from_gauge/:site_code', to: 'rivers#unsubscribe_from_gauge', as: 'unsubscribe'

  post '/rivers/update_subscription', to: 'rivers#update_subscription', as: 'update'

  get '/rivers/by_state/:state', to: 'rivers#index', as: 'get_rivers_by_state'
  post '/rivers/by_state', to: 'rivers#post_to_state', as: 'rivers_by_state'

  get '/rivers/by_name/:search', to: 'rivers#search', as: 'get_rivers_by_name'
  post '/rivers/by_name', to: 'rivers#post_to_name', as: 'rivers_by_name'

  get '/rivers/by_state_and_name/:state/:search', to: 'rivers#search', as: 'get_rivers_by_state_and_name'
  post '/rivers/by_state_and_name', to: 'rivers#post_to_state_and_name', as: 'rivers_by_state_by_name'

  resources :rivers, :except => :index

  get '/users/sign_in', to: 'devise/sessions#new', as: 'sign_in'
  get '/users/sign_up', to: 'devise/registrations#new', as: 'sign_up'
  match '/users/sign_out', to: 'devise/sessions#destroy', as: 'sign_out', via: 'delete'
  get '/users/:id', to: 'users#show', as: 'user_profile'

  resources :users

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href='http://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=PT+Sans+Narrow' rel='stylesheet' type='text/css'>
    <%= favicon_link_tag 'favicon.ico' %>


  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>

    <script type="text/javascript">
      function initialize() {
        google.maps.visualRefresh = true;
        var map = new google.maps.Map(document.getElementById('googft-mapCanvas'), {
          center: new google.maps.LatLng(38.8282, -97.5795),
          zoom: 4,
          mapTypeId: google.maps.MapTypeId.HYBRID,
          scrollwheel: false
        });

        layer = new google.maps.FusionTablesLayer({
          map: map,
          heatmap: { enabled: false },
          query: {
            select: "col3",
            from: "1IUTYCJ2oJko4KSiNcFbcwPeEkUHkTyETih1s-WM",
            where: ""
          },
          options: {
            styleId: 3,
            templateId: 3
          }
        });
      }

      google.maps.event.addDomListener(window, 'load', initialize);
      google.maps.event.addDomListener(window, 'page:load', initialize);
      </script>
    <%= yield :head %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="large-7 columns text-left">
         <h1><%= link_to 'Current Conditions', root_path, class: 'brand' %></h1>
        </div>
        <div class="large-5 columns">
            <% if user_signed_in? != true %>
          <ul class="button-group right">
              <li><%= link_to 'Sign In', sign_in_path, class: 'button' %></li>
              <li><%= link_to 'Register', sign_up_path, class: 'button' %></li>
          </ul>
            <% end %>
          <% if user_signed_in? %>
          <ul class="button-group2 right">
              <li id='sign-in-as'>Signed in as <%= current_user.email %></li><br>
              <li><%= link_to 'My Profile', user_profile_path(current_user), class: 'button' %></li>
              <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'button' %></li>
          </ul>
            <% end %>
        </div>
      </div>

      <div class="row">
        <div class="large-12 columns">
          <% if notice %>
            <p class="alert alert-notice"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-error"><%= alert %></p>
          <% end %>
        </div>
      </div>

      <div class='YIELD'>
        <%= yield %>
      </div>

      <footer class="row">
        <div class="large-12 columns">
          <hr />
          <div class="row">
            <div class="large-6 columns footer-link">
              <%= link_to "&copy; Made with love at Portland Code School :)".html_safe, 'http://www.portlandcodeschool.com' %>

            </div>
            <div class="large-6 columns">
              <ul class="inline-list right footer-link">
                <% if user_signed_in? != true %>
                  <li><%= link_to 'Sign In', sign_in_path %></li>
                  <li><%= link_to 'Register', sign_up_path %></li>
                <% end %>
                <% if user_signed_in? %>
                  <li><%= link_to 'My Profile', user_profile_path(current_user) %></li>
                  <li><%= link_to "Edit Profile", edit_user_registration_path(current_user) %></li>
                  <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </footer>

    <%= javascript_include_tag "application" %>
  </div>
  <!-- Do not remove the following line. Tests will break!
  Places a hidden marker for testing routes. -->
  <div class="hide"><%= params[:controller] + ':' + params[:action] %></div>
  </body>
</html>